### ISSUE TITLE
Neoforge support for mod stats

### ISSUE THREAD

**Issue by SuperStormer** [CurseForgeCommunity/CFLookup#13]
[NeoForge](https://neoforged.net/) (the successor to the Forge project) currently doesn't show up on https://cflookup.com/MinecraftModStats

**Comment by itssimple** [comment]
As it is not yet available in the API, I cannot add this. But it will be added, as soon as their API supports it.

**Comment by SuperStormer** [comment]
It is—it's just not documented yet. NeoForge's "ModLoaderType" id is 6.

**Comment by itssimple** [comment]
Ah, ok. Thanks. Will tell them to update the docs. Currently on vacation, but will add it as soon as I'm back at home, near a computer.

**Comment by itssimple** [comment]
Still no update on the docs/swagger, which is why I haven't done anything yet. Want to also release a new version of the [.NET API Client](https://github.com/CurseForgeCommunity/.NET-APIClient), but need them to update their docs (I'm asking them to do that since.. a while back)

**Comment by itssimple** [comment]
Solving this by manually adding the modloader, as the docs aren't getting updated anytime soon.
