### ISSUE TITLE
What API should I use to get information of Mod using ProjectID ?

### ISSUE THREAD

**Issue by jamols09** [CurseForgeCommunity/CFLookup#19]
I was wondering how were you able to get the mod description by using the slug or projectID? I can't find these in the curseforge documentation.

**Comment by itssimple** [comment]
Hey!

I use this endpoint to get the mod description: https://docs.curseforge.com/#get-mod-description (`https://api.curseforge.com/v1/mods/{modId}/description`)
And this one for mod information in general: https://docs.curseforge.com/#get-mod (`https://api.curseforge.com/v1/mods/{modId}`)

So for instance, my own modpack would have this: 
- https://api.curseforge.com/v1/mods/688687
- https://api.curseforge.com/v1/mods/688687/description

**Comment by jamols09** [comment]
@itssimple In order to get the modId I first need to find it right?
For example using only this link `https://www.curseforge.com/minecraft/mc-mods/clay-overhaul`

How were you able to retrieve the modID?
Because I think that `projectID` does not work with `/v1/mods/{modId}` API

**Comment by itssimple** [comment]
The project id found on the mod page, is the `modId`.

But as for searching with slugs, I have a very manual approach, where I split the URL into segments, and get `game`, `class` and `slug`.

https://github.com/CurseForgeCommunity/CFLookup/blob/master/CFLookup/Pages/Index.cshtml.cs#L164-L172

And then I have code that fetches the game info (all of it) and all categories for all games, and then I use that to search for mods with a matching slug.

https://github.com/CurseForgeCommunity/CFLookup/blob/master/CFLookup/SharedMethods.cs#L199-L236

**Comment by jamols09** [comment]
Thank you for the clarification. That was the confusion all along. `modID` = `projectID`
